-- 1
SELECT c1.CNAME, c1.CNUM
FROM CUST c1
WHERE c1.RATING >= ALL (
    SELECT c2.RATING
    FROM CUST c2
    WHERE c2.CITY = c1.CITY
);

-- 2
SELECT DISTINCT s.SNUM, s.SNAME
FROM SAL s
JOIN CUST c ON s.CITY = c.CITY
LEFT JOIN ORD o ON o.SNUM = s.SNUM AND o.CNUM = c.CNUM
WHERE o.ONUM IS NULL;

SELECT s.SNUM, s.SNAME
FROM SAL s
WHERE EXISTS (
    SELECT 1
    FROM CUST c
    WHERE c.CITY = s.CITY
    AND NOT EXISTS (
        SELECT 1
        FROM ORD o
        WHERE o.SNUM = s.SNUM
            AND o.CNUM = c.CNUM
    )
);